apiVersion: v1
kind: Service
metadata:
  name: haisin-app
  labels:
    app: haisin-app
spec:
  ports:
    - name: haisin-app
      protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: haisin-app
    tier: app
