apiVersion: apps/v1
kind: Deployment
metadata:
  name: haisin-app
  labels:
    app: haisin-app
spec:
  selector:
    matchLabels:
      app: haisin-app
      tier: app
  replicas: 2
  template:
    metadata:
      labels:
        app: haisin-app
        tier: app
    spec:
      containers:
      - name: haisin-app
        image: haisin-official/backend:latest
        imagePullPolicy: "IfNotPresent"
        envFrom:
          - secretRef:
              name: haisin-app-secret
          - secretRef:
              name: haisin-postgres-secret
          - secretRef:
              name: haisin-redis-secret
        ports:
          - containerPort: 8000
            name: app
            targetPort: 8000
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
