apiVersion: v1
kind: PersistentVolume
metadata:
  name: haisin-postgres-pv
  labels:
    type: local
    app: haisin-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/haisin/postgres"
  persistentVolumeReclaimPolicy: Retain
