apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: haisin_postgres_pv_claim
  labels:
    app: haisin_postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
