apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: haisin-postgres-pv-claim
  labels:
    app: haisin-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
