version: "3.9"

services:
  backend:
    container_name: haisin_backend
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    tty: true
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - type: bind
        source: .
        target: /go/app
    networks:
      - haisin_network

networks:
  haisin_network:
