apiVersion: batch/v1
kind: Job
metadata:
  name: haisin-migration
  labels:
    app: haisin-migration
spec:
  template:
    metadata:
      labels:
        app: haisin-migration
        tier: migrates
    spec:
      containers:
      - name: haisin-migration
        image: registry.nyao.me/library/haisin-migration:v1
        imagePullPolicy: IfNotPresent
        command: ["/atlas", "migrate", "apply", "--url", "$(DB_URL)"]
        envFrom:
          - secretRef:
              name: haisin-migration-secret
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
      restartPolicy: Never
  backoffLimit: 1