apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: haisin-redis-pv-claim
  labels:
    app: haisin-redis
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
