apiVersion: v1
kind: Service
metadata:
  name: haisin-redis
  labels:
    app: haisin-redis
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: haisin-redis
    tier: redis
