apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: haisin_redis_pv_claim
  labels:
    app: haisin_redis
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
