version: "3.8"

services:
  server:
    build:
      dockerfile: ./docker/server/Dockerfile.dev
    tty: true
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
    volumes:
      - ./app/server:/app/server
    ports:
      - 8080:8080
  mysql:
    build:
      dockerfile: ./docker/mysql/Dockerfile.dev
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
  redis:
    build:
      dockerfile: ./docker/redis/Dockerfile.dev
    ports:
      - 6379:6379

volumes:
  mysql_data:
    name: mysql_data