// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Service is the predicate function for service builders.
type Service func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
