FROM mysql:8.0-debian

# Set environment variables
# It should be override by compose.yaml !!!
ENV MYSQL_DATABASE=database
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=rootp@assw0rd
ENV MYSQL_ROOT_PASSWORD=rootp@assw0rd

# Copy SQL script to initialize database
COPY ./docker/mysql/init.sql /docker-entrypoint-initdb.d/
